name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    needs: [cypress-run]
    runs-on: ubuntu-latest
    steps:
      - name: Use actions/checkout@v2
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags - needed for `auto`
          # Default: 1
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Handle Cache
        uses: actions/cache@v2
        # https://github.com/actions/cache/blob/master/examples.md#node---lerna
        id: cache # use this to check for `cache-hit` (`steps.cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            node_modules
            **/node_modules
            ~/.cache/yarn
          key: node-deps-${{ hashFiles('yarn.lock') }}
          # restore-keys: node-deps-
      - name: Install Deps
        if: steps.cache.outputs.cache-hit != 'true'
        # This command clears the cache before installing dependences
        run: |
          yarn cache clean
          yarn install --immutable
        env:
          CYPRESS_INSTALL_BINARY: 0 # skipping big Cypress binary download. may cause problems later & need to remove or handle other ways. trying to keep CI speedy
      - name: Run Full Build
        run: yarn build
      - name: Run Knapsack Test
        run: yarn ks:test
